version: "3.9"
services:
  web:
    build: .
    ports: 
      - "3001:3001"
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data: {}